version: "3"
services:
  mqtt:
    image: iqtlabs/edgetech-mqtt:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped
  s3-uploader:
    image: iqtlabs/edgetech-s3-uploader:latest
    build:
      context: ./s3-uploader
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:?error}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:?error}
    env_file:
      - .env
    volumes:
      - /home/mobian/sensor-data:/sensor-data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    depends_on: 
      - mqtt